# 0-4   NUMERO...
# 5-7   OP_LOGICO...
tokens = ["NUMERO","IDENTIFICADOR","PALABRA_RESERVADA","OP_ARITMETICO","OP_RELACIONAL",
          "OP_LOGICO","SIMBOLO","ASIGNACION"]

# 0-4       ENTERO...
# 5-9       WHILE...
# 10-14     MAIN...
# 15-19     MULTIPLICACION...
# 20-24     MENOR_IGUAL...
# 25-29     AND...
# 30-34     LLAVE_D...
sub_tokens = ["ENTERO","REAL","IF","ELSE","DO",
              "WHILE","SWITCH","CASE","INTEGER","DOUBLE",
              "MAIN","CIN","COUT","SUMA","RESTA",
              "MULTIPLICACION","DIVISION","MODULO","POTENCIA","MENOR",
              "MENOR_IGUAL","MAYOR","MAYOR_IGUAL","DIFERENTE","IGUAL",
              "AND","OR","PARENTESIS_I","PARENTESIS_D","LLAVE_I",
              "LLAVE_D","COMA","PUNTO_Y_COMA","INCREMENTO","DECREMENTO"]

palabras_reservadas = ["if","else","do","while","switch","case","integer","double","main","cin","cout"]
